# welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,32,7]],np.int64)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

**array creation:conversion from other python structures**

In [9]:
listarray=np.array([[1,2,3],[5,6,7],[8,6,7]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 7]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({23,44,55})

array({44, 23, 55}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(1,5,12)

In [20]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
emp =np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78146625e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.78022206e-306, 8.34451503e-308, 2.22507386e-306]])

In [23]:
emp_like= np.empty_like(lspace)

In [24]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
ide= np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr=np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr=arr.reshape(3,33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
x = [[1,2,3],[5,6,7],[8,6,7]] 

In [34]:
ar=np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 7]])

In [36]:
ar.sum(axis=0)

array([14, 14, 17])

In [37]:
ar.sum(axis=1)

array([ 6, 18, 21])

In [38]:
ar.T

array([[1, 5, 8],
       [2, 6, 6],
       [3, 7, 7]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
5
6
7
8
6
7


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.nbytes

36

In [44]:
one= np.array([1,4,5,6])

In [45]:
one.argmax()

3

In [46]:
one.argmin()

0

In [47]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [48]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 7]])

In [49]:
ar.argmin()

0

In [50]:
ar.argmax()

6

In [51]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [52]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [53]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [54]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [55]:
ar.ravel()

array([1, 2, 3, 5, 6, 7, 8, 6, 7])

In [56]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8],
       [6],
       [7]])

In [57]:
ar2=np.array([[3,4,5],[6,7,3,],[9,3,4]])

In [58]:
ar+ar2

array([[ 4,  6,  8],
       [11, 13, 10],
       [17,  9, 11]])

In [59]:
[234,23]+[45,76]

[234, 23, 45, 76]

In [60]:
ar*ar2

array([[ 3,  8, 15],
       [30, 42, 21],
       [72, 18, 28]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 2.44948974, 2.64575131]])

In [62]:
ar.sum()

45

In [63]:
ar.max()

8

In [64]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 7]])

In [66]:
np.where(ar>5)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [67]:
np.count_nonzero(ar)

9

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [69]:
import sys

In [70]:
py_ar=[2,3,4,6]

In [72]:
np_ar= np.array(py_ar)

In [73]:
sys.getsizeof(1)*len(py_ar)

112

In [74]:
np_ar.itemsize*np_ar.size

16